// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;

namespace GeometricFigure_Interface
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Создание фигур
            GeometricFigure triangle = new Triangle("Треугольник", 3, 4, 5);
            GeometricFigure square = new Square("Квадрат", 10);

            triangle.Print();
            Console.WriteLine("===================");
            square.Print();
            CompoundFigure compoundFigure = new CompoundFigure();
            compoundFigure.AddFigure(triangle);
            compoundFigure.AddFigure(square);
            Console.WriteLine("===================");
            Console.WriteLine($"Общая площадь: {compoundFigure.GetArea()}");
            Console.WriteLine($"Общий периметр: {compoundFigure.GetPerimeter()}");
            
            Triangle triangle1 = new Triangle("Треугольник", 3, 4, 5);
            triangle1.Draw();

            
        }
    }
};