// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;

namespace GeometricFigure_Interface
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Создание фигур
            GeometricFigure triangle = new Triangle("Треугольник", 3, 4, 5);
            GeometricFigure square = new Square("Квадрат", 10);
            
            // Тестирование методов Print
            triangle.Print();
            Console.WriteLine("===================");
            square.Print();
            
            // Создание сцены и добавление фигур
            Scene scene = new Scene();
            scene.AddFigure(triangle);
            scene.AddFigure(square);
            
            // Тестирование метода DrawScene
            Console.WriteLine("===================");
            Console.WriteLine("Отрисовка сцены:");
            scene.DrawScene();
            
        }
    }
};